// Copyright (c) 2022 Marco Wang <m.aesophor@gmail.com>. All rights reserved.
#ifndef HAVOC_C_SEQUENCES_H_
#define HAVOC_C_SEQUENCES_H_

enum CSequences {
  DEFAULT_DRAW = 0,
  DEFAULT_IDLE1 = 1,
  DEFAULT_IDLE2 = 2,
  DEFAULT_LIGHT_MISS1 = 3,
  DEFAULT_LIGHT_MISS2 = 4,
  DEFAULT_HEAVY_MISS1 = 9,
  DEFAULT_HEAVY_HIT1 = 10,
  DEFAULT_HEAVY_BACKSTAB = 11,
  DEFAULT_LOOKAT01 = 12,

  BUTTERFLY_DRAW = 0,
  BUTTERFLY_DRAW2 = 1,
  BUTTERFLY_LOOKAT01 = 13,
  BUTTERFLY_LOOKAT03 = 15,

  FALCHION_IDLE1 = 1,
  FALCHION_HEAVY_MISS1 = 8,
  FALCHION_HEAVY_MISS1_NOFLIP = 9,
  FALCHION_LOOKAT01 = 12,
  FALCHION_LOOKAT02 = 13,

  DAGGERS_IDLE1 = 1,
  DAGGERS_LIGHT_MISS1 = 2,
  DAGGERS_LIGHT_MISS5 = 6,
  DAGGERS_HEAVY_MISS2 = 11,
  DAGGERS_HEAVY_MISS1 = 12,

  BOWIE_IDLE1 = 1,
};

#endif  // HAVOC_C_SEQUENCES_H_
